### ISSUE TITLE
[SITE REQ] filehaus.top

### ISSUE THREAD

**Issue by M4RCK5** [Official-Husko/mul-tor#42] opened 2024-06-22 13:54 UTC
**Please give me the links that apply below**
Main Website: https://filehaus.top/
API URL:  None.

**Please fill out the information below:**

- [ ] This site has an API
- [ ] This site requires an account
- [ ] This site is requires a subscription
- [ ] I would be willing to give a premium account to add the site

**Is there anything else you would like to add that might help me?**
None.

**Comment by Official-Husko** [comment] 2024-06-22 15:19
duplicate of #37

**Closed by Official-Husko** 2024-06-22 15:19 UTC
Labels: enhancement
